mass: 10.0
model: desistek_saga
inertial:
  ixx: 0.27
  iyy: 0.56
  izz: 0.52
  ixy: 0.0
  ixz: 0.0
  iyz: 0.0
cog: [0, 0, 0]
# CoB represented wrt ENU convention
cob: [0, 0, 0.155]
volume: 0.011054
length: 0.448
height: 0.28066
width: 0.2384
base_link: base_link
Ma:
- [1.7, 0, 0, 0, 0, 0]
- [0, 0, 0, 0, 0, 0]
- [0, 0, 5.5, 0, 0, 0]
- [0, 0, 0, 0.0, 0, 0]
- [0, 0, 0, 0, 1.2, 0]
- [0, 0, 0, 0, 0, 0.5]
# In the model, the damping coefficients are pre-multiplied by -1
linear_damping: [-10, -20, -30, -25, -45, -5]
quad_damping: [0, 0, 0, 0, 0, 0]
density: 1028.0
