<?xml version="1.0"?>
<!-- Copyright (c) 2016 The UUV Simulator Authors.
     All rights reserved.

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find uuv_descriptions)/urdf/common.urdf.xacro"/>
  <xacro:include filename="$(find uuv_sensor_ros_plugins)/urdf/sensor_snippets.xacro"/>
  <xacro:include filename="$(find desistek_saga_description)/urdf/desistek_saga_snippets.xacro"/>
  <xacro:include filename="$(find uuv_gazebo_ros_plugins)/urdf/snippets.xacro"/>

  <!-- Parameters -->
  <xacro:property name="mass" value="10"/>
  <xacro:property name="volume" value="0.011054"/>
  <!-- <xacro:property name="cog" value="0 0 0.02535"/> -->
  <xacro:property name="cog" value="0 0 0"/>
  <xacro:property name="cob" value="0 0 0.155"/>
  <xacro:property name="rho" value="1028"/>

  <xacro:property name="x_size" value="0.448"/>
  <xacro:property name="y_size" value="0.2384"/>
  <xacro:property name="z_size" value="0.28066"/>

  <xacro:property name="equivalent_radius" value="${0.5*z_size}"/>

  <xacro:property name="visual_mesh_file" value="file://$(find desistek_saga_description)/mesh/saga.dae"/>
  <xacro:property name="collision_mesh_file" value="file://$(find desistek_saga_description)/mesh/saga.stl"/>

  <xacro:macro name="desistek_saga_base" params="namespace debug inertial_reference_frame">

  <link name="${namespace}/base_link">
    <inertial>
      <mass value="${mass}" />
      <origin xyz="${cog}" rpy="0 0 0"/>
      <inertia ixx="${0.2*mass*y_size*y_size + 0.2*mass*z_size*z_size}" ixy="0.0" ixz="0.0"
               iyy="${0.2*mass*x_size*x_size + 0.2*mass*z_size*z_size}" iyz="0.0"
               izz="${0.2*mass*x_size*x_size + 0.2*mass*y_size*y_size}" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="${visual_mesh_file}" scale="1 1 1" />
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="${collision_mesh_file}" scale="1 1 1" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="${namespace}/base_link">
    <selfCollide>false</selfCollide>
  </gazebo>

    <!-- Set up hydrodynamic plugin -->
    <gazebo>
      <plugin name="${namespace}_uuv_plugin" filename="libuuv_underwater_object_ros_plugin.so">
        <fluid_density>${rho}</fluid_density>
        <flow_velocity_topic>hydrodynamics/current_velocity</flow_velocity_topic>
        <debug>${debug}</debug>
        <link name="${namespace}/base_link">
          <neutrally_buoyant>1</neutrally_buoyant>
          <volume>${volume}</volume>
          <box>
            <width>${y_size}</width>
            <length>${x_size}</length>
            <height>${z_size}</height>
          </box>
          <center_of_buoyancy>${cob}</center_of_buoyancy>
          <hydrodynamic_model>
            <type>fossen</type>
            <added_mass>
              1.7182 0 0 0 0 0
              0 0 0 0 0 0
              0 0 5.468 0 0 0
              0 0 0 0 0 0
              0 0 0 0 1.2481 0
              0 0 0 0 0 0.4006
            </added_mass>
            <linear_damping>
              -11.7391 -20 -31.8678 -25 -44.9085 -5
            </linear_damping>
            <quadratic_damping>
              0 0 0 0 0 0
            </quadratic_damping>
          </hydrodynamic_model>
        </link>
      </plugin>
    </gazebo>

    <xacro:include filename="$(find desistek_saga_description)/urdf/desistek_saga_thrusters.xacro"/>
    <xacro:include filename="$(find desistek_saga_description)/urdf/desistek_saga_sensors.xacro"/>

  </xacro:macro>

</robot>
